<?php

namespace LaraDevs\Spanish\Tests\Lang;

use Illuminate\Support\Facades\Artisan;
use LaraDevs\Spanish\Tests\TestCase;

class EsTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app['config']->set('app.locale', 'es');

        Artisan::call('laradevs:spanish');
    }

    /** @test */
    public function it_translate_error_auth(){
        $this->assertEquals(
            trans('auth.failed'),
            'Estas credenciales no coinciden con nuestros registros.'
        );
    }

    /** @test */
    public function it_translatet_name()
    {
        $this->assertEquals(
            __('Name'),
            'Nombre'
        );
    }

    /** @test */
    public function it_format_json_correct()
    {
        $fileJson = join(DIRECTORY_SEPARATOR, array(
            dirname(__FILE__),
            '..',
            '..',
            'resources',
            'lang',
            'es.json'
        ));

        $jsonData = file_get_contents($fileJson);

        $this->assertJson($jsonData);

        foreach (json_decode($jsonData, true) as $key => $translate) {
            $this->assertEquals(
                __($key),
                $translate
            );
        }
    }
}
